project:
  type: website

website:
  title: "ISSS624"
  navbar:
    left: 
      - text: Hands-on Exercise
        menu: 
          - text: Hands-on Exercise 1
            href: Hands-on_Ex/Hands-on_Ex1/Hands-on_Ex1.html
          - text: Hands-on Exercise 1a
            href: Hands-on_Ex/Hands-on_Ex1a/Hands-on_Ex1a.html
          - text: Hands-on Exercise 2
            href: Hands-on_Ex/Hands-on_Ex2/Hands-on_Ex2.html
          - text: Hands-on Exercise 2a
            href: Hands-on_Ex/Hands-on_Ex2a/Hands-on_Ex2a.html
          - text: Hands-on Exercise 2b
            href: Hands-on_Ex/Hands-on_Ex2b/Hands-on_Ex2b.html
      - text: In-class Exercise
        menu: 
          - text: In-class Exercise 1
            href: In-class_Ex/In-class_Ex1/In-class_Ex1.html
          - text: In-class Exercise 2
            href: In-class_Ex/In-class_Ex2/In-class_Ex2.html
          - text: In-class Exercise 2a
            href: In-class_Ex/In-class_Ex2a/In-class_Ex2a.html
          - text: In-class Exercise 2b
            href: In-class_Ex/In-class_Ex2b/In-class_Ex2b.html
      - text: Take-home Exercise
        menu: 
          - text: Take-home Exercise 1
            href: Take-home_Ex/Take-home_Ex1/Take-home_Ex1.html
          - text: Take-home Exercise 2
            href: Take-home_Ex/Take-home_Ex2/Take-home_Ex2.html
    right:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

