---
title: "In-class Exercise 1: My First Date with Geospatial Data Analytics"
date: "18 November 2023"
date-modified: "last-modified"
format: html
execute:
  echo: true
  eval: true
  warning: false
editor: visual
---

## Getting Started

The code chunk below loads the following packages:

-   tmap: for thematic mapping
-   sf: for geospatial data handling
-   tidyverse: for non-spatial data handling

```{r}
pacman:: p_load(tmap, sf, tidyverse)
```

###importing

Firstly , we will import that *Passenger Volume By Origin Destination Bus Stops* data set dowonloaded from LTA Datamall by using `read_csv()` of **readr** package

```{r}
#|eval: false
odbus <- read_csv("data/aspatial/origin_destination_bus_202308.csv")
```

```{r}
#|eval: false
odbus$ORIGIN_PT_CODE <- as.factor(odbus$ORIGIN_PT_CODE)
odbus$DESTINATION_PT_CODE <- as.factor(odbus$DESTINATION_PT_CODE)

```

```{r}
#|eval: false
origintrip_7_9 <- odbus %>%
  filter (Day_Type == "WEEKDAY") %>%
  filter (TIME_PER_HOUR >= 7 & TIME_PER_HOUR <=9) %>%
  group_by(ORIGIN_PTE_CODE) %>%
  summarise(TRIPS = sum(TOTAL_TRIPS))
```

```{r}
#|eval: false
bustop <- st_read(dsn = "data/geospatial)", layer = "BusStop") %>%
  st_transform(crs = 3414)
```

```{r}
#|eval: false
mpsz <- st_read(dsn = "data/geospatial)", layer = "MPSZ-2019") %>%
 
mpsz
```
